"use client";

import Head from "next/head";
import { Header } from "../ui/Header";

import { Container } from "@chakra-ui/react";
import { ChakraProvider } from "@chakra-ui/react";

import "../styles/globals.css";
import "@code-hike/mdx/dist/index.css";
import "@code-hike/mini-browser/dist/index.css";

import { theme } from "../lib/theme";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ChakraProvider theme={theme}>
          <Header />
          <Container maxW={"7xl"}>
            <Head>
              <title>Rah.codes</title>
              <meta name="description" content="Generated by Rahsheen Porter" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
          </Container>
        </ChakraProvider>
      </body>
    </html>
  );
}
